In [ ]:
import pandas as pd
import re
df = pd.read_csv("arxiv.csv")

In [ ]:
# new columns
df = df[["submitter",
        "title",
        "abstract", "categories"]]
df

,submitter,title,abstract,categories
0,Pavel Nadolsky,Calculation of prompt diphoton production cros...,A fully differential calculation in perturba...,hep-ph
1,Louis Theran,Sparsity-certifying Graph Decompositions,"We describe a new algorithm, the $(k,\ell)$-...",math.CO cs.CG
2,Hongjun Pan,The evolution of the Earth-Moon system based o...,The evolution of Earth-Moon system is descri...,physics.gen-ph
3,David Callan,A determinant of Stirling cycle numbers counts...,We show that a determinant of Stirling cycle...,math.CO
4,Alberto Torchinsky,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,In this paper we show how to compute the $\L...,math.CA math.FA
...,...,...,...,...
1747302,Ruslan Prozorov,On the origin of the irreversibility line in t...,We report on measurements of the angular dep...,supr-con cond-mat.supr-con
1747303,Durga P. Choudhury,Nonlinear Response of HTSC Thin Film Microwave...,The non-linear microwave surface impedance o...,supr-con cond-mat.supr-con
1747304,Durga P. Choudhury,Critical State Flux Penetration and Linear Mic...,The vortex contribution to the dc field (H) ...,supr-con cond-mat.supr-con
1747305,Hasegawa Yasumasa,Density of States and NMR Relaxation Rate in A...,We show that the density of states in an ani...,supr-con cond-mat.supr-con
1747306,Masanori Ichioka,Ginzburg Landau theory for d-wave pairing and ...,The Ginzburg Landau theory for d_{x^2-y^2}-w...,supr-con cond-mat.supr-con

In [ ]:
def map_category(categories_str):
    if not isinstance(categories_str, str):
        return "Unknown"

    primary_label = categories_str.split(' ')[0]

    # --- REGLAS DE MAPEO ---

    # 1. Prefijos Estándar con punto
    if primary_label.startswith('cs.'): return 'Computer Science'
    if primary_label.startswith('math.'): return 'Mathematics'
    if primary_label == 'math-ph': return 'Mathematics' # Alias de math.MP
    if primary_label.startswith('stat.'): return 'Statistics'
    if primary_label.startswith('q-bio.'): return 'Quantitative Biology'
    if primary_label.startswith('q-fin.'): return 'Quantitative Finance'
    if primary_label.startswith('eess.'): return 'Electrical Engineering'
    if primary_label.startswith('econ.'): return 'Economics'

    # prefijosfisica
    physics_prefixes = [
        'astro-ph', 'cond-mat', 'gr-qc', 'hep-ex', 'hep-lat', 'hep-ph',
        'hep-th', 'nucl-ex', 'nucl-th', 'physics', 'quant-ph', 'nlin',
        'acc-phys', # Accelerator Physics
        'supr-con', 'chao-dyn', 'adap-org', 'comp-gas', 'patt-sol',
        'solv-int', 'mat-ph', 'chem-ph'
    ]
    if any(primary_label.startswith(p) for p in physics_prefixes):
        return 'Physics'

    #mas prefijos
    if primary_label in ['alg-geom', 'dg-ga', 'funct-an', 'q-alg']: return 'Mathematics'
    if primary_label == 'cmp-lg': return 'Computer Science'
    if primary_label == 'bayes-an': return 'Statistics'

    return 'Other'
df['macro_cat'] = df['categories'].apply(map_category)

/var/folders/lt/n0_y0qx173v13mss419tfhlm0000gn/T/ipykernel_43475/2514052668.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['macro_cat'] = df['categories'].apply(map_category)

In [ ]:
df

,submitter,title,abstract,categories,macro_cat
0,Pavel Nadolsky,Calculation of prompt diphoton production cros...,A fully differential calculation in perturba...,hep-ph,Physics
1,Louis Theran,Sparsity-certifying Graph Decompositions,"We describe a new algorithm, the $(k,\ell)$-...",math.CO cs.CG,Mathematics
2,Hongjun Pan,The evolution of the Earth-Moon system based o...,The evolution of Earth-Moon system is descri...,physics.gen-ph,Physics
3,David Callan,A determinant of Stirling cycle numbers counts...,We show that a determinant of Stirling cycle...,math.CO,Mathematics
4,Alberto Torchinsky,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,In this paper we show how to compute the $\L...,math.CA math.FA,Mathematics
...,...,...,...,...,...
1747302,Ruslan Prozorov,On the origin of the irreversibility line in t...,We report on measurements of the angular dep...,supr-con cond-mat.supr-con,Physics
1747303,Durga P. Choudhury,Nonlinear Response of HTSC Thin Film Microwave...,The non-linear microwave surface impedance o...,supr-con cond-mat.supr-con,Physics
1747304,Durga P. Choudhury,Critical State Flux Penetration and Linear Mic...,The vortex contribution to the dc field (H) ...,supr-con cond-mat.supr-con,Physics
1747305,Hasegawa Yasumasa,Density of States and NMR Relaxation Rate in A...,We show that the density of states in an ani...,supr-con cond-mat.supr-con,Physics
1747306,Masanori Ichioka,Ginzburg Landau theory for d-wave pairing and ...,The Ginzburg Landau theory for d_{x^2-y^2}-w...,supr-con cond-mat.supr-con,Physics

In [ ]:
print("CONTEO POR MACRO CATEGORÍA:")
print(df['macro_cat'].value_counts())

num_others = df[df['macro_cat'] == 'Other'].shape[0]
print(f"Total de filas en 'Other': {num_others}")
if num_others > 0:
    print("\n CATEGORÍAS EN 'OTHER'")
    print(df[df['macro_cat'] == 'Other']['categories'].unique()[:20])
else:
    print("\n¡Excelente! No hay categorías sin clasificar.")

CONTEO POR MACRO CATEGORÍA:
macro_cat
Physics                   1039837
Mathematics                390284
Computer Science           244029
Statistics                  29340
Quantitative Biology        19886
Electrical Engineering      14153
Quantitative Finance         7743
Economics                    1761
Other                         274
Name: count, dtype: int64
Total de filas en 'Other': 274

 CATEGORÍAS EN 'OTHER'
['ao-sci physics.ao-ph' 'ao-sci cond-mat physics.ao-ph'
 'ao-sci physics.ao-ph physics.flu-dyn' 'atom-ph physics.atom-ph'
 'atom-ph chem-ph physics.atom-ph'
 'atom-ph physics.atom-ph physics.optics quant-ph'
 'atom-ph chem-ph math.QA nucl-th physics.atom-ph q-alg'
 'atom-ph chem-ph cond-mat physics.atom-ph'
 'atom-ph chem-ph physics.atom-ph quant-ph'
 'atom-ph chem-ph cond-mat physics.atom-ph quant-ph'
 'atom-ph cond-mat physics.atom-ph' 'atom-ph physics.atom-ph plasm-ph'
 'atom-ph physics.atom-ph quant-ph' 'atom-ph astro-ph physics.atom-ph'
 'atom-ph hep-ph physics.atom-ph'
 'atom-ph cond-mat physics.atom-ph quant-ph' 'mtrl-th cond-mat.mtrl-sci'
 'mtrl-th chem-ph cond-mat.mtrl-sci'
 'mtrl-th atom-ph chem-ph cond-mat.mtrl-sci' 'plasm-ph physics.plasm-ph']

SAMPLEO, QUITARE LOS PAPERS QUE SE CLASIFICARON COMO OTHER, REDUCIRE EL TAMAÑO DEL DATASET POR CUESTIONES DE TIEMPO AL EJECUTAR MODELOS.

CREARE UNA VARIABLE LLAMADA CATEGORIA PRIMARIA

In [ ]:
from sklearn.model_selection import train_test_split

df['macro_cat'] = df['categories'].apply(map_category)

df['primary_cat'] = df['categories'].apply(lambda x: x.split(' ')[0] if isinstance(x, str) else 'Unknown')

#quitare los papers que no pude categorizar en macro categoria
df_clean = df[df['macro_cat'] != 'Other'].copy()

#filtrar clases pequeñas
counts = df_clean["primary_cat"].value_counts()
valid_categories = counts[counts >= 2].index
df_clean = df_clean[df_clean['primary_cat'].isin(valid_categories)]

print(f"dimensiones antes del sample:  {df_clean.shape}")

#muestreo stratificado por primary_cat
#al estratificar por lo mas especifico, proteges al modelo b y modelo a
print("generando sample estratificado")

df_sample, _ = train_test_split(
    df_clean,
    train_size= 0.10,   #10% del dataset
    stratify=df_clean["primary_cat"],
    random_state=42
)

print(f"Tamaño del sample final: {df_sample.shape}")

# Verificación rápida:
print("\nTop 5 subcategorías en el sample:")
print(df_sample['primary_cat'].value_counts(normalize=True).head())

dimensiones antes del sample:  (1747033, 6)
generando sample estratificado
Tamaño del sample final: (174703, 6)

Top 5 subcategorías en el sample:
primary_cat
hep-ph               0.064435
astro-ph             0.053949
hep-th               0.051596
quant-ph             0.044390
cond-mat.mes-hall    0.028586
Name: proportion, dtype: float64

PRIMARY_CAT (NIVEL 2(ESPECIFICAS)) PARA EL MODELO B
MACRO_CAT NIVEL (1 (GENERAL)) PARA MODELO A

In [ ]:
!pip install spacy

Collecting spacy
  Downloading spacy-3.8.11-cp313-cp313-macosx_11_0_arm64.whl.metadata (27 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.7 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.12-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.5 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.10-cp313-cp313-macosx_11_0_arm64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.5.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.4.2 (from spacy)
  Downloading weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typer-slim<1.0.0,>=0.3.0 (from spacy)
  Downloading typer_slim-0.20.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.10.3)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (72.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.7.14)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (7.5 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Using cached confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: click>=8.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.1.8)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.4.1)
Requirement already satisfied: wrapt in /opt/anaconda3/lib/python3.13/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->spacy) (3.0.2)
Downloading spacy-3.8.11-cp313-cp313-macosx_11_0_arm64.whl (5.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 544.8 kB/s eta 0:00:00a 0:00:01
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.13-cp313-cp313-macosx_11_0_arm64.whl (42 kB)
Downloading murmurhash-1.0.15-cp313-cp313-macosx_11_0_arm64.whl (27 kB)
Downloading preshed-3.0.12-cp313-cp313-macosx_11_0_arm64.whl (122 kB)
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.2-cp313-cp313-macosx_11_0_arm64.whl (651 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 651.7/651.7 kB 402.8 kB/s eta 0:00:00a 0:00:01
Downloading thinc-8.3.10-cp313-cp313-macosx_11_0_arm64.whl (737 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 737.1/737.1 kB 162.8 kB/s eta 0:00:00a 0:00:02
Downloading blis-1.3.3-cp313-cp313-macosx_11_0_arm64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 1.8 MB/s eta 0:00:00a 0:00:01
Using cached confection-0.1.5-py3-none-any.whl (35 kB)
Downloading typer_slim-0.20.0-py3-none-any.whl (47 kB)
Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.3-py3-none-any.whl (50 kB)
Downloading cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Installing collected packages: wasabi, typer-slim, spacy-loggers, spacy-legacy, murmurhash, cymem, cloudpathlib, catalogue, blis, srsly, preshed, confection, weasel, thinc, spacy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [spacy]m14/15 [spacy]gue]
Successfully installed blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.23.0 confection-0.1.5 cymem-2.0.13 murmurhash-1.0.15 preshed-3.0.12 spacy-3.8.11 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.2 thinc-8.3.10 typer-slim-0.20.0 wasabi-1.1.3 weasel-0.4.3

In [ ]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 1.0 MB/s eta 0:00:0000:01:00:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [ ]:
import spacy
import pandas as pd
from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:
class ArxivCleaner:
    def __init__(self):
        # cargar spacy
        try:
            self.nlp = spacy.load("en_core_web_sm", disable=['ner', 'lemmatizer'])
        except OSError:
            print("Modelo no encontrado.")
            raise

        #stopwords a mantener
        scientific_keep = {
            "however", "therefore", "thus", "hence", "consequently",
            "furthermore", "moreover", "nevertheless", "meanwhile",
            "otherwise", "via", "whereas", "whereby", "propose", "method",
            "using", "present", "significant", "analysis"
        }
        self.custom_stopwords = STOP_WORDS - scientific_keep

        # --- REGEX ---
        self.url_pattern = re.compile(r'http\S+|www\S+|https\S+')
        self.doi_pattern = re.compile(r'\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?!["&\'<>])\S)+)\b')
        self.ref_pattern = re.compile(r'\[\d+(?:-\d+)?(?:,\s*\d+)*\]')

        # LaTeX: Bloques entre $...$ o $$...$$ (soporta saltos de linea con DOTALL)
        self.latex_pattern = re.compile(r'\$\$?.*?\$\$?', re.DOTALL)

        # Comandos LaTeX sueltos (ej: \sigma, \alpha, \frac)
        self.latex_command_pattern = re.compile(r'\\[a-zA-Z]+')

    def _clean_text_single(self, text):
        if not text or not isinstance(text, str):
            return ""

        #  BORRADO DE LATEX (Reemplazo por espacio en blanco)
        text = self.latex_pattern.sub(' ', text)
        text = self.latex_command_pattern.sub(' ', text)

        # limpieza dois y urls
        text = self.url_pattern.sub('', text)
        text = self.doi_pattern.sub('', text)
        text = self.ref_pattern.sub('', text)

        # quitamos caracteres no ascii
        text = re.sub(r'[^\x00-\x7F]+', ' ', text)

        # espacios dobles
        text = re.sub(r'\s+', ' ', text).strip()

        # procesamiento spacy
        doc = self.nlp(text)
        cleaned_tokens = []

        for token in doc:
            if token.is_space: continue
            if token.text.lower() in self.custom_stopwords: continue
            # Conservar guiones intra-palabra
            if token.is_punct and not (token.text == '-' and token.i > 0 and token.i < len(doc)-1): continue

            word = token.text

            # Eliminar símbolos matemáticos sueltos que hayan quedado (+, =, ^, >)
            if word in {'+', '=', '^', '>', '<', '~', '|', '*', '%'}:
                continue

            # Lógica de mayúsculas/números
            if word.isupper() and len(word) > 1:
                final_word = word
            elif token.like_num:
                final_word = word
            else:
                final_word = word.lower()

            # Filtro de ruido: palabras de 1 letra (excepto 'a' o 'i' o números)
            if len(final_word) < 2 and final_word not in ['a', 'i'] and not final_word.isdigit():
                continue

            if final_word.strip():
                cleaned_tokens.append(final_word)

        return " ".join(cleaned_tokens)

    def process_dataframe(self, df, output_col='cleaned_text'):
        if 'title' not in df.columns or 'abstract' not in df.columns:
            raise ValueError("Faltan columnas 'title' o 'abstract'")

        print("Procesando DataFrame (Eliminando LaTeX)...")
        df_clean = df.copy()

        # Concatenación Title + . + Abstract
        df_clean['temp_raw'] = (
            df_clean['title'].fillna('').astype(str).str.strip() +
            ". " +
            df_clean['abstract'].fillna('').astype(str).str.strip()
        )

        df_clean[output_col] = df_clean['temp_raw'].apply(self._clean_text_single)
        df_clean.drop(columns=['temp_raw'], inplace=True)

        print(f"Listo. Columna '{output_col}' creada.")
        return df_clean

In [ ]:
cleaner = ArxivCleaner()
cleaned = cleaner.process_dataframe(df_sample)
cleaned.to_csv("cleaned.csv", index=False)
print("Proceso terminado.")

Procesando DataFrame (Eliminando LaTeX)...
Listo. Columna 'cleaned_text' creada.
Proceso terminado.

In [ ]:
CLEANED_PATH = "cleaned.csv"
cleaned = pd.read_csv(CLEANED_PATH)

In [ ]:
cleaned

,submitter,title,categories,abstract,macro_cat,primary_cat,cleaned_text
0,Matthias Neubert,Threshold Resummation in Momentum Space from E...,hep-ph,Methods from soft-collinear effective theory...,Physics,hep-ph,threshold resummation momentum space effective...
1,J. A. Sauls,Phase Modulated Thermal Conductance of Josephs...,cond-mat.supr-con,We present a theory for quasiparticle heat t...,Physics,cond-mat.supr-con,phase modulated thermal conductance josephson ...
2,Marco Bertola,Symplectic extensions of the Kirillov-Kostant ...,math-ph math.MP math.SG nlin.SI,We revisit symplectic properties of the mono...,Mathematics,math-ph,symplectic extensions kirillov kostant goldman...
3,Michael Fink,An Algebra of Causal Chains,cs.AI,In this work we propose a multi-valued exten...,Computer Science,cs.AI,algebra causal chains work propose multi value...
4,Zhonghui You,Gate Decorator: Global Filter Pruning Method f...,cs.CV cs.LG eess.IV,Filter pruning is one of the most effective ...,Computer Science,cs.CV,gate decorator global filter pruning method ac...
...,...,...,...,...,...,...,...
174698,Maury Bramson,Network stability under max--min fair bandwidt...,math.PR,There has recently been considerable interes...,Mathematics,math.PR,network stability max min fair bandwidth shari...
174699,Subo Dong,Directly Imaging Tidally Powered Migrating Jup...,astro-ph.EP,Upcoming direct-imaging experiments may dete...,Physics,astro-ph.EP,directly imaging tidally powered migrating jup...
174700,Yi Liao,Lepton Mixing Matrix in Standard Model Extende...,hep-ph,We consider the simplest extension of the st...,Physics,hep-ph,lepton mixing matrix standard model extended s...
174701,Somil Bansal,Hamilton-Jacobi Reachability: A Brief Overview...,cs.SY math.DS math.OC,Hamilton-Jacobi (HJ) reachability analysis i...,Computer Science,cs.SY,hamilton jacobi reachability brief overview re...
174702,Vyacheslav Shatokhin,Coherence turned on by incoherent light,quant-ph,One of the most pertinent problems in the de...,Physics,quant-ph,coherence turned incoherent light pertinent pr...

VEAMOS SI SE LIMPIO BIEN

In [ ]:
# randomrow
random_paper = cleaned.sample(1).iloc[0]

print("=== 1. TÍTULO ORIGINAL ===")
print(random_paper['title'])
print("\n=== 2. ABSTRACT ORIGINAL ===")
print(random_paper['abstract'])

print("\n" + "="*60) # Línea separadora

print("=== 3. TEXTO LIMPIO (Concatenado y Procesado) ===")
print(random_paper['cleaned_text'])

print("\n" + "="*60)


print("Verificación de reglas:")
original_len = len(str(random_paper['title'])) + len(str(random_paper['abstract']))
clean_len = len(str(random_paper['cleaned_text']))
reduction = (1 - clean_len/original_len) * 100

print(f"- Reducción de tamaño: {reduction:.1f}% (aprox)")
if "however" not in random_paper['cleaned_text'].split() and "however" in random_paper['abstract'].lower():
     print("- Stopwords científicas ('however'): ELIMINADAS correctamente")
else:
     print("- Stopwords: No se detectó 'however' en el original o no se eliminó (revisar caso).")

=== 1. TÍTULO ORIGINAL ===
A Detailed Thermal Analysis of the Binospec Spectrograph

=== 2. ABSTRACT ORIGINAL ===
  Refractive optics in astronomical instruments are potentially sensitive to
temperature gradients and temperature transients. This sensitivity arises from
thermally dependent refractive indices, lens spacings, and lens dimensions. We
have therefore undertaken a detailed thermal analysis of Binospec, a wide-field
optical spectrograph under development for the converted MMT. Our goals are to
predict the temperature gradients that will be present in the Binospec optics
and structure under realistic operating conditions and to determine how design
choices affect these gradients. We begin our analysis by deriving thermal time
constants for instrument subassemblies. We then generate a low-resolution
finite difference model of the entire instrument and high-resolution models of
sensitive subassemblies. This approach to thermal analysis is applicable to a
variety of other instruments. We use measurements of the ambient temperature in
the converted MMT's dome to model Binospec's thermal environment. During
moderate conditions we find that the Binospec lens groups develop 0.14 C axial
and radial temperature gradients and that lens groups of different mass develop
0.5 C temperature differences; these numbers are doubled for the extreme
conditions. Internal heat sources do not significantly affect these results;
heat flow from the environment dominates. The instrument must be periodically
opened to insert new aperture masks, but we find that the resulting temperature
gradients and thermal stresses in the optics are small. Image shifts at the
detector caused by thermal deflections of the Binospec optical bench structure
are approx 0.1 pixel/hr. We conclude that the proposed Binospec design has
acceptable thermal properties, and briefly discuss design changes to further
reduce temperature gradients.


============================================================
=== 3. TEXTO LIMPIO (Concatenado y Procesado) ===
detailed thermal analysis binospec spectrograph refractive optics astronomical instruments potentially sensitive temperature gradients temperature transients sensitivity arises thermally dependent refractive indices lens spacings lens dimensions therefore undertaken detailed thermal analysis binospec wide field optical spectrograph development converted MMT goals predict temperature gradients present binospec optics structure realistic operating conditions determine design choices affect gradients begin analysis deriving thermal time constants instrument subassemblies generate low resolution finite difference model entire instrument high resolution models sensitive subassemblies approach thermal analysis applicable variety instruments use measurements ambient temperature converted MMT dome model binospec thermal environment moderate conditions find binospec lens groups develop 0.14 axial radial temperature gradients lens groups different mass develop 0.5 temperature differences numbers doubled extreme conditions internal heat sources significantly affect results heat flow environment dominates instrument periodically opened insert new aperture masks find resulting temperature gradients thermal stresses optics small image shifts detector caused thermal deflections binospec optical bench structure approx 0.1 pixel hr conclude proposed binospec design acceptable thermal properties briefly discuss design changes reduce temperature gradients

============================================================
Verificación de reglas:
- Reducción de tamaño: 22.1% (aprox)
- Stopwords: No se detectó 'however' en el original o no se eliminó (revisar caso).